### ISSUE TITLE
Add API for partially applied requests

### ISSUE THREAD

**Issue by raygesualdo** [Legitcode/legible#15]
I opened this issue to begin discussion on the "requestable" feature. 

Initial thoughts:
- It might need a more descriptive name, such as "partial" or "requestPartial". IMHO, "requestable" doesn't clearly communicate what it's doing under the hood.
- I don't know if we need a `.attach` API. Assuming they're declared according to the example in the README, partially applied requests could be used like so:
```javascript
//using the library
import twitter from './tweets'

twitter.register`
  body: ${{ email: 'test@test.com', password: 'Tester' }}
`
```

**Comment by zackify** [comment]
We can call it partial. I would say partial takes a Template string
obviously, then returns another function expecting the Template strings for
when actually using it, then merges the two values.

**Comment by zackify** [comment]
We could make this really easily actually. Just merge the outputted
objects.

**Comment by zackify** [comment]
I'll make a pr tomorrow with an example!

**Comment by raygesualdo** [comment]
Sounds great! I'll be on the lookout.
