### ISSUE TITLE
Remove colons?

### ISSUE THREAD

**Issue by zackify** [Legitcode/legible#18]
```js
const twitter = {
  register: partial`
    url https://api.twitter.com/register,
    method POST
  `
}
```
Thoughts?

**Comment by raygesualdo** [comment]
I'm not a huge fan. I think the semicolons are helpful both visually and syntactically. Is there a specific reason you'd want to remove them?

**Comment by zackify** [comment]
nope, just curious. I agree with you. Did you happen to see the partial requests PR?

**Comment by raygesualdo** [comment]
I did and left some comments on the files. Liked it as a whole and agree we need to pull the actual request handling out.

**Comment by zackify** [comment]
I didnt see the comments. Weird.
