### ISSUE TITLE
Enforce code formatting

### ISSUE THREAD

**Issue by raygesualdo** [Legitcode/legible#4]
Thoughts on establishing a consitent format throughout the project? It will become especially helpful as more contributors add code. I would suggest [standard](https://github.com/feross/standard) for this. The code is 98% of the way there as it sits now (just ran a test locally). If you think it's a good idea, I'll submit a PR with standard and the changes to get the code at 100% adherence.

**Comment by zackify** [comment]
Sure, go for it. Thanks for all the help!

**Comment by raygesualdo** [comment]
No problem. About to PR.
